spring:
  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower: follower-channel
        achievement: achievement-channel
        event_channel:
          name: event-start-channel
        mentorship_requested_channel:
          name: mentorship-requested-channel
        comment_channels:
          name: comments-channel
        mentorship: mentorship-accepted-channel
        skill_channel:
          name: skill-offered-channel

  mail:
    host: smtp.gmail.com
    port: 587
    username: xxx@gmail.com
    #https://www.baeldung.com/spring-email
    password: xxx
    #https://support.google.com/mail/answer/7104828?hl=en&rd=3&visit_id=638195765566773400-3814427644
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages

  async:
    scheduled:
      thread-pool:
        core_pool_size: 2
        max_pool_size: 2

server:
  port: 8083

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

user-service:
  host: localhost
  port: 8080